### ISSUE TITLE
New Users throwing inconsistent error

### ISSUE THREAD

**Issue by amarbut24** [microsoftgraph/msgraph-sdk-go#203]
Hello,

I'm using this SDK to create new Azure AD users
`newUser, err := c.Users().Post(requestBody)` is a snippet of the code I'm using

While testing the code in my lab there are times when the Post will randomly fail
I've extracted the error Code and Message when it fails
```
Code=BadRequest
message=Unable to read JSON request payload. Please ensure Content-Type header is set and payload is of valid JSON format.
```
There aren't any failures logged in Azure (which makes sense based on the error)

I'm wondering why (if anything) can be done to prevent this error
As I said the error is very intermittent. If I run the code again right away it might succeed. 

For example, I added a test to range over 5 users and create them. If I run it 10-15 times I would say every time I run it I'll get at least 1-2 failures. There is no rhyme or reason which users will fail. I suppose I could write my own retry where if that error presents itself it just tries again, but figured I would reach out in case I'm missing something

**Comment by baywet** [comment]
Hi @amarbut24 
Thanks for reaching out and for trying the Go SDK.
Unless there's a service issue I'm not aware of, this error usually indicates that the JSON sent to the API is invalid. It'd be strange that retrying a non-transient issue would make it work. Are you sure the payload your application is setting is not changing from one try to another? Do you have any important difference between users? (fields being set, character sets etc.)
FYI, we've fixed a number of issues in with serialization over the last few weeks, please make sure you're on the latest version of the SDK (0.28.0 at the time of writing) which should also pull the latest version of the JSON package (0.5.3).

**Comment by amarbut24** [comment]
Hey @baywet 
I have a theory now that I'm thinking about it. When creating these test users I'm generating random passwords.
Do you have a list of accepted characters for Azure AD user passwords handy? I wonder if that is what's causing the issue.

Thanks,
Anthony

**Comment by amarbut24** [comment]
That was it.... I had a `\` in the random password I was generating.
Sorry for the noise here

Feel free to close this one out

**Comment by baywet** [comment]
Thank you for getting to the bottom of this. What version of the serialization lib (this) do you have? Are you having the same problem with latest? (0.5.3)
If so I'd argue it's a bug and the backslash character should be escaped to generate a valid payload

**Comment by amarbut24** [comment]
Hey @baywet 

I made to use the latest serialization lib `0.5.3` and am still seeing the behavior 

Did some more testing and I feel confident in saying the issue is tied to using `\` in the password. I created 10 users a few times.
I outputted the password used for failed creations and there is a pattern. 

I'm going to share the output as these were test accounts and have already been deleted (I changed the domain in as well)
```
2022/06/22 17:24:42 failed to concurrently create testuser6@contoso.onmicrosoft.com with err call failed - password used was _R/2\hJNE^eb1[N^uq
2022/06/22 17:24:42 failed to concurrently create testuser8@contoso.onmicrosoft.com with err call failed - password used was /(UG\AUEmv':GE#wJS
2022/06/22 17:24:42 created new user testuser3@contoso.onmicrosoft.com
2022/06/22 17:24:42 created new user testuser2@contoso.onmicrosoft.com
2022/06/22 17:24:42 created new user testuser4@contoso.onmicrosoft.com
2022/06/22 17:24:42 created new user testuser5@contoso.onmicrosoft.com
2022/06/22 17:24:42 created new user testuser7@contoso.onmicrosoft.com
2022/06/22 17:24:42 created new user testuser0@contoso.onmicrosoft.com
```

this behavior is consistent. If I remove `\` as an option in the password generation I never get a new user failure.

**Comment by baywet** [comment]
Thanks for confirming.
The fix needs to be implemented [here]https://github.com/microsoft/kiota-serialization-json-go/blob/e5b31bc06f4f1591c632b927e404ab1b69528065/json_serialization_writer.go#L30)

a unit test could be implemented [here](https://github.com/microsoft/kiota-serialization-json-go/blob/main/json_parse_node_test.go)

and lastly the changelog needs to be updated [here]https://github.com/microsoft/kiota-serialization-json-go/blob/main/CHANGELOG.md) (let's bump to 0.5.4)

Is this something you'd be willing to submit a pull request for?

**Comment by amarbut24** [comment]
Hey @baywet ,

Yeah more than happy to. I'm a bit new to Go so might take a few to figure out, but I'll give it a go (pun intended)

**Comment by amarbut24** [comment]
Hey @baywet 

Sorry for the delay. Life has been busy the last few days. Was going to attempt to PR a fix this week, but can wait if another user is going to knock it out

**Comment by baywet** [comment]
It is really up to you, we're looking at multiple issues with dadams39 so it might be a while, if you think you can quickly put together a PR, go for it. We'll handle merge conflicts if any if necessary.

**Comment by dadams39** [comment]
@amarbut24 , feel free to work on the issue. I'm going to be away for a few days. Even if I wasn't, your perspective and insight would only improve the other repository. https://github.com/microsoft/kiota-serialization-json-go/issues/30 is going to stay open for a little while longer yet. This portion of the code hasn't been looked at yet.

**Comment by amarbut24** [comment]
Hey @baywet ,

I gave this an honest effort yesterday and not sure how to proceed. 

So the issue is related to when we use a `\` in a password. 
As you called out,[ this bit of code](https://github.com/microsoft/kiota-serialization-json-go/blob/e5b31bc06f4f1591c632b927e404ab1b69528065/json_serialization_writer.go#L30) is replacing `\` with `\\`, effectly escaping the backslash.

I did some debugging and confirmed everything is working as expected
Using `_R/2\hJNE^eb1[N^uq` as a password, here is the json blob that was generated
```
"{\"accountEnabled\":false,\"displayName\":\"Test User0\",\"mailNickname\":\"testuser0\",\"passwordProfile\":{\"forceChangePasswordNextSignIn\":true,\"password\":\"_R/2\\hJNE^eb1[N^uq"},\"userPrincipalName\":\"testuser0@gopherland.onmicrosoft.com\"}"
```
So is the goal here to change how we're espacing the backslash? 
I'm having trouble wrapping my ahead around what we need to do to backslashes to make sure the json blob is validate, as double backslash `\\` I _thought_ was the way to approach it.

**Comment by baywet** [comment]
@amarbut24 that's ok, thanks for giving it a try! I've authored https://github.com/microsoft/kiota-serialization-json-go/pull/33 to expedite this issue. Thanks everyone for the feedback and the support here!

**Comment by amarbut24** [comment]
Oh 🤦‍♂️  I wasn't looking at the original replace close enough
```
s := `\`
fmt.Println("single quote:", s)
s = strings.ReplaceAll(s, "\\", "\\\\")
fmt.Println("after replace:", s)

o := "\""
fmt.Println("original replace: ", o)
w := "\\\""
fmt.Println("original replace with: ", w)

---------------------------
single quote: \
after replace: \\
original replace:  "
original replace with:  \"
```

Alright, this makes sense to me now.
Hopefully next time I run across something I'll be able to just PR a fix myself.

**Comment by baywet** [comment]
FYI the release (0.5.4) was just published.
